---
version: "2.0"

services:
  web:
    image: avolon42x/d3akash.cloud:release-v0.1.1
    expose:
      - port: 80
        as: 80
        accept:
          - www.d3akash.cloud
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.3
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    dcloud:
      attributes:
        host: d3akash.cloud
      signedBy:
        anyOf:
          
      pricing:
        web:
          denom: uakt
          amount: 1

deployment:
  web:
    dcloud:
      profile: web
      count: 1
